# Generated by Django 4.1 on 2024-11-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Laptop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                ("processor", models.CharField(max_length=100)),
                ("ram_size", models.PositiveIntegerField()),
                ("storage_size", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("release_date", models.DateField()),
            ],
        ),
    ]
